"""
initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2025-07-23 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('nickname', sa.String(), nullable=False, unique=True)
    )
    op.create_table('admin_users',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('login', sa.String(), nullable=False, unique=True),
        sa.Column('password_hash', sa.String(), nullable=False)
    )
    op.create_table('sessions',
        sa.Column('session_id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('player_id', sa.Integer(), sa.ForeignKey('players.id'), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('ended_at', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('balance', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('unsold_stocks', sa.JSON(), nullable=False)
    )
    op.create_table('stocks',
        sa.Column('symbol', sa.String(), primary_key=True, nullable=False),
        sa.Column('company_name', sa.String(), nullable=False),
        sa.Column('sector', sa.String(), nullable=True),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('available_from', sa.Date(), nullable=True),
        sa.Column('available_to', sa.Date(), nullable=True)
    )
    op.create_table('session_selections',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('session_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('sessions.session_id'), nullable=False),
        sa.Column('popular_symbol', sa.String(), sa.ForeignKey('stocks.symbol'), nullable=False),
        sa.Column('volatile_symbol', sa.String(), sa.ForeignKey('stocks.symbol'), nullable=False),
        sa.Column('sector_symbol', sa.String(), sa.ForeignKey('stocks.symbol'), nullable=False)
    )
    op.create_table('trades',
        sa.Column('trade_id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('session_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('sessions.session_id'), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('symbol', sa.String(), sa.ForeignKey('stocks.symbol'), nullable=False),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('qty', sa.Integer(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('session_selections')
    op.drop_table('stocks')
    op.drop_table('sessions')
    op.drop_table('admin_users')
    op.drop_table('players')
    # ### end Alembic commands ###