"""remove unique constraint from player nickname

Revision ID: 6737ca3a3851
Revises: 0002_stock_prices_sectors
Create Date: 2025-07-27 12:49:05.009004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6737ca3a3851'
down_revision: Union[str, Sequence[str], None] = '0002_stock_prices_sectors'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.drop_constraint(op.f('players_nickname_key'), 'players', type_='unique')
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_session_selections_id'), 'session_selections', ['id'], unique=False)
    op.alter_column('stock_prices', 'symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('stock_prices', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('stock_prices', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_foreign_key(None, 'stock_prices', 'stocks', ['symbol'], ['symbol'])
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_trade_id'), 'trades', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_trade_id'), table_name='trades')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_constraint(None, 'stock_prices', type_='foreignkey')
    op.alter_column('stock_prices', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stock_prices', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('stock_prices', 'symbol',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_session_selections_id'), table_name='session_selections')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.create_unique_constraint(op.f('players_nickname_key'), 'players', ['nickname'])
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    # ### end Alembic commands ###
